In [ ]:
problem statement: 
- déterminer un nombre de poses optimales pour les mesures
- déterminer les critères optimum pour chaque pose

- input : matrice de keypoint (de dimension n : nombre d'image par gif)
- modèle : déterminer l'image optimale 
- output : image du GIF présentant la meilleure pose


In [ ]:
- déterminer un nombre de poses optimales pour les mesures


- déterminer les critères optimum pour chaque pose - Get input from API (Jerem)


- input : matrice de keypoint (output 17 lignes 3 colonnes  / n img )

                               
- modèle : déterminer l'image optimale 

- output : image du GIF présentant la meilleure pose

In [145]:
import pandas as pd
import numpy as np
import math

# Test with 1 image, 17 lines, 3 columns

In [35]:
matrice_test = np.random.random((17,6))
matrice_test

array([[0.56266164, 0.21639547, 0.5210022 , 0.46156277, 0.06484895,
        0.43838658],
       [0.49759833, 0.97413891, 0.22887355, 0.90544964, 0.13565894,
        0.15778135],
       [0.57966439, 0.40765158, 0.99231706, 0.19992918, 0.40711584,
        0.68093439],
       [0.99240452, 0.0142952 , 0.94514886, 0.53787177, 0.8292834 ,
        0.9162937 ],
       [0.69153743, 0.87684952, 0.12468775, 0.14348886, 0.52297273,
        0.65545206],
       [0.67601232, 0.08508023, 0.25029933, 0.50473955, 0.74819125,
        0.72423877],
       [0.77018248, 0.31611694, 0.04502545, 0.56583307, 0.95159535,
        0.7583452 ],
       [0.98949557, 0.55206663, 0.32679285, 0.47439483, 0.30324134,
        0.60616536],
       [0.29858718, 0.55636036, 0.41993484, 0.47855843, 0.87079314,
        0.71975756],
       [0.38502044, 0.30052528, 0.97314585, 0.49698869, 0.69002271,
        0.83608304],
       [0.98270117, 0.56457562, 0.9337942 , 0.84419016, 0.105305  ,
        0.47088544],
       [0.19980084, 0

In [36]:
df = pd.DataFrame(matrice_test)

In [37]:
df.shape

(17, 6)

In [38]:
df["key_points"]=['nose',
                           'left_eye', 'right_eye',
                            'left_ear', 'right_ear',
                            'left_shoulder', 'right_shoulder',
                            'left_elbow', 'right_elbow',
                            'left_wrist', 'right_wrist',
                            'left_hip', 'right_hip',
                            'left_knee', 'right_knee',
                            'left_ankle', 'right_ankle',                            
]
df.set_index('key_points', inplace=True)
df

0         1         2         3         4         5
key_points                                                                
nose            0.562662  0.216395  0.521002  0.461563  0.064849  0.438387
left_eye        0.497598  0.974139  0.228874  0.905450  0.135659  0.157781
right_eye       0.579664  0.407652  0.992317  0.199929  0.407116  0.680934
left_ear        0.992405  0.014295  0.945149  0.537872  0.829283  0.916294
right_ear       0.691537  0.876850  0.124688  0.143489  0.522973  0.655452
left_shoulder   0.676012  0.085080  0.250299  0.504740  0.748191  0.724239
right_shoulder  0.770182  0.316117  0.045025  0.565833  0.951595  0.758345
left_elbow      0.989496  0.552067  0.326793  0.474395  0.303241  0.606165
right_elbow     0.298587  0.556360  0.419935  0.478558  0.870793  0.719758
left_wrist      0.385020  0.300525  0.973146  0.496989  0.690023  0.836083
right_wrist     0.982701  0.564576  0.933794  0.844190  0.105305  0.470885
left_hip        0.199801  0.046398  0.448360  0.252042  0.104998  0.296277
right_hip       0.764042  0.626470  0.362293  0.163550  0.935403  0.105127
left_knee       0.807209  0.015443  0.621438  0.666702  0.894918  0.299612
right_knee      0.840140  0.487729  0.821838  0.610252  0.984052  0.739806
left_ankle      0.319771  0.055390  0.442291  0.600408  0.950699  0.608780
right_ankle     0.239226  0.581517  0.710769  0.195761  0.006841  0.406442

In [39]:
df.columns = ['image1_x', "image1_y", 'image2_x', "image2_y", 'image3_x', "image3_y"]
df

image1_x  image1_y  image2_x  image2_y  image3_x  image3_y
key_points                                                                
nose            0.562662  0.216395  0.521002  0.461563  0.064849  0.438387
left_eye        0.497598  0.974139  0.228874  0.905450  0.135659  0.157781
right_eye       0.579664  0.407652  0.992317  0.199929  0.407116  0.680934
left_ear        0.992405  0.014295  0.945149  0.537872  0.829283  0.916294
right_ear       0.691537  0.876850  0.124688  0.143489  0.522973  0.655452
left_shoulder   0.676012  0.085080  0.250299  0.504740  0.748191  0.724239
right_shoulder  0.770182  0.316117  0.045025  0.565833  0.951595  0.758345
left_elbow      0.989496  0.552067  0.326793  0.474395  0.303241  0.606165
right_elbow     0.298587  0.556360  0.419935  0.478558  0.870793  0.719758
left_wrist      0.385020  0.300525  0.973146  0.496989  0.690023  0.836083
right_wrist     0.982701  0.564576  0.933794  0.844190  0.105305  0.470885
left_hip        0.199801  0.046398  0.448360  0.252042  0.104998  0.296277
right_hip       0.764042  0.626470  0.362293  0.163550  0.935403  0.105127
left_knee       0.807209  0.015443  0.621438  0.666702  0.894918  0.299612
right_knee      0.840140  0.487729  0.821838  0.610252  0.984052  0.739806
left_ankle      0.319771  0.055390  0.442291  0.600408  0.950699  0.608780
right_ankle     0.239226  0.581517  0.710769  0.195761  0.006841  0.406442

In [65]:
df["image1_x"]

key_points
nose              0.562662
left_eye          0.497598
right_eye         0.579664
left_ear          0.992405
right_ear         0.691537
left_shoulder     0.676012
right_shoulder    0.770182
left_elbow        0.989496
right_elbow       0.298587
left_wrist        0.385020
right_wrist       0.982701
left_hip          0.199801
right_hip         0.764042
left_knee         0.807209
right_knee        0.840140
left_ankle        0.319771
right_ankle       0.239226
Name: image1_x, dtype: float64

In [102]:
im1_x = df["image1_x"]
im1_x = pd.DataFrame(im1_x)
im1_x

image1_x
key_points              
nose            0.562662
left_eye        0.497598
right_eye       0.579664
left_ear        0.992405
right_ear       0.691537
left_shoulder   0.676012
right_shoulder  0.770182
left_elbow      0.989496
right_elbow     0.298587
left_wrist      0.385020
right_wrist     0.982701
left_hip        0.199801
right_hip       0.764042
left_knee       0.807209
right_knee      0.840140
left_ankle      0.319771
right_ankle     0.239226

In [106]:
im1_x.index

Index(['nose', 'left_eye', 'right_eye', 'left_ear', 'right_ear',
       'left_shoulder', 'right_shoulder', 'left_elbow', 'right_elbow',
       'left_wrist', 'right_wrist', 'left_hip', 'right_hip', 'left_knee',
       'right_knee', 'left_ankle', 'right_ankle'],
      dtype='object', name='key_points')

In [112]:
im1_x['image1_x']['left_shoulder']

0.676012316379324

In [122]:
list_arms_1 = []
for i in im1_x.index:
    if i == 'left_shoulder' or i == 'right_shoulder' or i=='left_elbow' or i== 'right_elbow' or i=='left_wrist' or i =='right_wrist':
        list_arms_1.append(im1_x['image1_x'][i])
list_arms_1

[0.676012316379324,
 0.7701824762346423,
 0.9894955669719383,
 0.29858718337262713,
 0.38502044226610876,
 0.982701170491575]

In [127]:
im2_x = df["image2_x"]
im2_x = pd.DataFrame(im2_x)
im2_x

image2_x
key_points              
nose            0.521002
left_eye        0.228874
right_eye       0.992317
left_ear        0.945149
right_ear       0.124688
left_shoulder   0.250299
right_shoulder  0.045025
left_elbow      0.326793
right_elbow     0.419935
left_wrist      0.973146
right_wrist     0.933794
left_hip        0.448360
right_hip       0.362293
left_knee       0.621438
right_knee      0.821838
left_ankle      0.442291
right_ankle     0.710769

In [130]:
list_arms_2 = []
for i in im2_x.index:
    if i == 'left_shoulder' or i == 'right_shoulder' or i=='left_elbow' or i== 'right_elbow' or i=='left_wrist' or i =='right_wrist':
        list_arms_2.append(im2_x['image2_x'][i])
list_arms_2

[0.25029932703094127,
 0.045025445353718885,
 0.32679285004302994,
 0.4199348416029497,
 0.9731458540222326,
 0.9337941954394284]

In [133]:
im3_x = df["image3_x"]
im3_x = pd.DataFrame(im3_x)
im3_x

image3_x
key_points              
nose            0.064849
left_eye        0.135659
right_eye       0.407116
left_ear        0.829283
right_ear       0.522973
left_shoulder   0.748191
right_shoulder  0.951595
left_elbow      0.303241
right_elbow     0.870793
left_wrist      0.690023
right_wrist     0.105305
left_hip        0.104998
right_hip       0.935403
left_knee       0.894918
right_knee      0.984052
left_ankle      0.950699
right_ankle     0.006841

In [134]:
list_arms_3 = []
for i in im3_x.index:
    if i == 'left_shoulder' or i == 'right_shoulder' or i=='left_elbow' or i== 'right_elbow' or i=='left_wrist' or i =='right_wrist':
        list_arms_3.append(im3_x['image3_x'][i])
list_arms_3

[0.7481912494502948,
 0.9515953526437398,
 0.3032413403500669,
 0.870793141589449,
 0.6900227094851374,
 0.10530500355295802]

In [136]:
list_arms = list(zip(list_arms_1,list_arms_2,list_arms_3))
list_arms

[(0.676012316379324, 0.25029932703094127, 0.7481912494502948),
 (0.7701824762346423, 0.045025445353718885, 0.9515953526437398),
 (0.9894955669719383, 0.32679285004302994, 0.3032413403500669),
 (0.29858718337262713, 0.4199348416029497, 0.870793141589449),
 (0.38502044226610876, 0.9731458540222326, 0.6900227094851374),
 (0.982701170491575, 0.9337941954394284, 0.10530500355295802)]

In [138]:
df_arms = pd.DataFrame(list_arms)
df_arms

0         1         2
0  0.676012  0.250299  0.748191
1  0.770182  0.045025  0.951595
2  0.989496  0.326793  0.303241
3  0.298587  0.419935  0.870793
4  0.385020  0.973146  0.690023
5  0.982701  0.933794  0.105305

In [142]:
df_arms[0].mean()

0.6836665259527025

In [150]:
df_arms[0].std()

0.29256530926473784

In [151]:
df_arms[1].std()

0.37878072647312466

# Selection criteria

#comment définir si quelqu'un est de face / de dos (max distance entre épaules)



#critère  profil - Mini distance entre les épaules + alignement entre

output format of tensors: 42 images / 17 points / 3 coordinates (X/Y/likelyhood)

42 / 1 / 1 / 17 / 3

## Criteria: someone is facing camera / (tbc if also valid if showing its front)

criteria: check on max distance on X and min distance on Y

In [160]:
# 'nose',                                   pos 0
#'left_eye', 'right_eye',                   pos 1 / 2
# 'left_ear', 'right_ear',                  pos 3 / 4
# 'left_shoulder', 'right_shoulder',        pos 5 / 6
# 'left_elbow', 'right_elbow',              pos 7 / 8
# 'left_wrist', 'right_wrist',              pos 9 / 10
# 'left_hip', 'right_hip',                  pos 11 / 12
# 'left_knee', 'right_knee',                pos 13 / 14
# 'left_ankle', 'right_ankle',              pos 15 / 16

In [154]:
keypoints_test = np.random.random((47,17,3))
keypoints_test

array([[[0.71390643, 0.44717513, 0.32174302],
        [0.80835382, 0.25937053, 0.25608216],
        [0.63099105, 0.77646639, 0.15029388],
        ...,
        [0.06410172, 0.96411482, 0.07929425],
        [0.02401791, 0.02063123, 0.90695511],
        [0.05069392, 0.77771327, 0.59106021]],

       [[0.1240782 , 0.85407834, 0.28978534],
        [0.1644787 , 0.52852075, 0.78461518],
        [0.07020176, 0.03849731, 0.13515064],
        ...,
        [0.68587721, 0.24881829, 0.93743318],
        [0.92719643, 0.11554893, 0.87426573],
        [0.35923887, 0.34633617, 0.78059705]],

       [[0.45773804, 0.82255902, 0.67206164],
        [0.0056978 , 0.59450969, 0.57390297],
        [0.51793828, 0.41410638, 0.55988547],
        ...,
        [0.69606991, 0.73108768, 0.06898255],
        [0.13643861, 0.37607511, 0.61579426],
        [0.37189609, 0.4555597 , 0.48446198]],

       ...,

       [[0.67062916, 0.23270021, 0.68866745],
        [0.46280844, 0.47137208, 0.91695626],
        [0.08580392, 0

In [250]:
keypoints_test[8]

array([[0.99705554, 0.29334207, 0.88257698],
       [0.09035994, 0.28032001, 0.18919667],
       [0.35889371, 0.59638294, 0.28780704],
       [0.63319123, 0.00253786, 0.50244901],
       [0.25531334, 0.63259549, 0.88996437],
       [0.0994313 , 0.86958704, 0.91789534],
       [0.91069091, 0.54409452, 0.71803188],
       [0.62013312, 0.21729998, 0.23779736],
       [0.51104028, 0.10653493, 0.67079428],
       [0.50064687, 0.50847285, 0.97218834],
       [0.15004028, 0.11245744, 0.18801611],
       [0.23898466, 0.54657969, 0.66269309],
       [0.18760644, 0.72307082, 0.24106981],
       [0.08302376, 0.16359791, 0.89191505],
       [0.83246736, 0.69266189, 0.10857395],
       [0.26061587, 0.53369352, 0.23118327],
       [0.75264985, 0.33795138, 0.12493599]])

In [233]:
distance_shoulder = []
horizontal_shoulder = []
horizontal_elbow = []
horizontal_wrist = []
horizontal_st_deviation = []

for image in keypoints_test:                                       #iterate on each image
    distance_shoulder.append(abs(image[5][0]-image[6][0]))         #calculate abs distance (on x) between 'left_shoulder', 'right_shoulder'
    horizontal_shoulder.append(abs(image[5][1]-image[6][1]))       #calculate abs distance (on y) between 'left_shoulder', 'right_shoulder'
    horizontal_elbow.append(abs(image[7][1]-image[8][1]))          #calculate abs distance (on y) between  elbows  
    horizontal_wrist.append(abs(image[9][1]-image[10][1]))         #calculate abs distance (on y) between  wrists
    

    
max_distance_x_index = distance_shoulder.index(max(distance_shoulder))         #index of image for max distance  on x shoulder
min_distance_y_index = horizontal_shoulder.index(min(horizontal_shoulder))     #index of image for min distance  on y shoulder

In [213]:
list_shoulderx_sort = sorted(distance_shoulder, reverse=True)
list_shoulderx_sort

[0.8112596102206585,
 0.7663636840159467,
 0.6905026545483369,
 0.6337683214373103,
 0.6299300747615119,
 0.5917638823610747,
 0.5832312127185528,
 0.5713718385233504,
 0.5549743920044922,
 0.5339732066252992,
 0.5173809441740697,
 0.4035844766626834,
 0.36158804884890394,
 0.3600310244644006,
 0.34851517305250135,
 0.33951350510374545,
 0.32623617277685035,
 0.30577120387235335,
 0.3052915903603046,
 0.28471162790474114,
 0.2846168897768314,
 0.26593582203219734,
 0.2348305856755536,
 0.2316720401649266,
 0.20448335639053883,
 0.20361385632996964,
 0.20107714612747685,
 0.16786495252897127,
 0.15988539495078968,
 0.1537240088783669,
 0.12338627566271065,
 0.12218439860604347,
 0.10800875128709331,
 0.10563523931682628,
 0.10328050363696317,
 0.10150998281982127,
 0.07312864002646446,
 0.054226761784006206,
 0.04968481830783833,
 0.04127273702758216,
 0.04091515207919805,
 0.03841263274515094,
 0.03683779450528102,
 0.031772762002017396,
 0.024347596113528436,
 0.017488494004744615,
 0

In [259]:
#image index considering ranking on shoulders max(x)
image_index_ranking_x = []
for i in list_shoulderx_sort:
    image_x_index = distance_shoulder.index(i)
    image_index_ranking_x.append(image_x_index)
image_index_ranking_x 

[8,
 28,
 1,
 17,
 21,
 2,
 35,
 15,
 46,
 32,
 44,
 4,
 24,
 5,
 10,
 26,
 25,
 12,
 37,
 3,
 27,
 0,
 23,
 39,
 40,
 19,
 9,
 31,
 42,
 41,
 29,
 6,
 22,
 13,
 30,
 33,
 20,
 14,
 16,
 45,
 18,
 43,
 34,
 36,
 38,
 7,
 11]

In [260]:
image_index_ranking_x_top10 = image_index_ranking_x[0 :9 ]
image_index_ranking_x_top10

[8, 28, 1, 17, 21, 2, 35, 15, 46]

In [262]:
keypoints_test_top10 = []
for i in image_index_ranking_x_top10:
    keypoints_test_top10.append(keypoints_test[i])
keypoints_test_top10
    

[array([[0.99705554, 0.29334207, 0.88257698],
        [0.09035994, 0.28032001, 0.18919667],
        [0.35889371, 0.59638294, 0.28780704],
        [0.63319123, 0.00253786, 0.50244901],
        [0.25531334, 0.63259549, 0.88996437],
        [0.0994313 , 0.86958704, 0.91789534],
        [0.91069091, 0.54409452, 0.71803188],
        [0.62013312, 0.21729998, 0.23779736],
        [0.51104028, 0.10653493, 0.67079428],
        [0.50064687, 0.50847285, 0.97218834],
        [0.15004028, 0.11245744, 0.18801611],
        [0.23898466, 0.54657969, 0.66269309],
        [0.18760644, 0.72307082, 0.24106981],
        [0.08302376, 0.16359791, 0.89191505],
        [0.83246736, 0.69266189, 0.10857395],
        [0.26061587, 0.53369352, 0.23118327],
        [0.75264985, 0.33795138, 0.12493599]]),
 array([[0.99967281, 0.3465736 , 0.66598142],
        [0.38069303, 0.82972121, 0.92047034],
        [0.88346475, 0.90898893, 0.79521324],
        [0.77912187, 0.92197365, 0.85523275],
        [0.84908635, 0.63893681,

In [263]:
horizontal_shoulder_top10 = []
for image in keypoints_test_top10:                                 #iterate on each image
    horizontal_shoulder_top10.append(abs(image[5][1]-image[6][1]))       #calculate abs distance (on y) between 'left_shoulder', 'right_shoulder'
horizontal_shoulder_top10 = sorted(horizontal_shoulder_top10, reverse=False)
horizontal_shoulder_top10


[0.02384719244079625,
 0.08150200985917144,
 0.1885897961130486,
 0.2549711513763301,
 0.32424477171406696,
 0.32549251996855866,
 0.4538936093836987,
 0.7315061046148806,
 0.9396282400338322]

In [264]:
#image index considering ranking on shoulders min(y)
image_index_rank_max_x_min_y = []
for i in horizontal_shoulder_top10:
    image_index_rank_max_x_min_y.append(horizontal_shoulder.index(i))
image_index_rank_max_x_min_y

[21, 46, 35, 17, 15, 8, 28, 2, 1]

### Old approach with no initial selection on x

In [247]:
list_shouldery_sort = sorted(horizontal_shoulder, reverse=False)
list_shouldery_sort

[0.02384719244079625,
 0.024353686869251545,
 0.030924475655899397,
 0.03987198981002171,
 0.0403670406012584,
 0.04272853480025429,
 0.05303771196621576,
 0.05385957973729294,
 0.05997394901296005,
 0.07367638137875931,
 0.07538869410519555,
 0.08150200985917144,
 0.0847814101415536,
 0.0887275222397832,
 0.14415817895149707,
 0.14670744611327236,
 0.15168761127265273,
 0.1885897961130486,
 0.22193163486022016,
 0.2342734624440852,
 0.2549711513763301,
 0.275444497368613,
 0.2759965774145564,
 0.32424477171406696,
 0.32549251996855866,
 0.32981085072127814,
 0.3476972382092325,
 0.3732153160144882,
 0.40820182580873476,
 0.40975508394758386,
 0.43501299566034846,
 0.4482013225233543,
 0.4538936093836987,
 0.46948186601705544,
 0.5190729454680353,
 0.5237948080242957,
 0.5299284252279659,
 0.5313139575184489,
 0.5424688738219573,
 0.5614863376197693,
 0.702065737744291,
 0.7121846649530144,
 0.7181981907917905,
 0.7315061046148806,
 0.7575286676418657,
 0.8412815805148686,
 0.939628240

In [248]:
list_shouldery_sort = sorted(horizontal_shoulder, reverse=False)
list_shouldery_sort

[0.02384719244079625,
 0.024353686869251545,
 0.030924475655899397,
 0.03987198981002171,
 0.0403670406012584,
 0.04272853480025429,
 0.05303771196621576,
 0.05385957973729294,
 0.05997394901296005,
 0.07367638137875931,
 0.07538869410519555,
 0.08150200985917144,
 0.0847814101415536,
 0.0887275222397832,
 0.14415817895149707,
 0.14670744611327236,
 0.15168761127265273,
 0.1885897961130486,
 0.22193163486022016,
 0.2342734624440852,
 0.2549711513763301,
 0.275444497368613,
 0.2759965774145564,
 0.32424477171406696,
 0.32549251996855866,
 0.32981085072127814,
 0.3476972382092325,
 0.3732153160144882,
 0.40820182580873476,
 0.40975508394758386,
 0.43501299566034846,
 0.4482013225233543,
 0.4538936093836987,
 0.46948186601705544,
 0.5190729454680353,
 0.5237948080242957,
 0.5299284252279659,
 0.5313139575184489,
 0.5424688738219573,
 0.5614863376197693,
 0.702065737744291,
 0.7121846649530144,
 0.7181981907917905,
 0.7315061046148806,
 0.7575286676418657,
 0.8412815805148686,
 0.939628240

In [223]:
#image index considering ranking on shoulders min(y)
image_index_ranking_y = []
for i in list_shouldery_sort:
    image_y_index = horizontal_shoulder.index(i)
    image_index_ranking_y.append(image_y_index)
image_index_ranking_y

[21,
 13,
 11,
 14,
 5,
 33,
 18,
 24,
 34,
 23,
 41,
 46,
 10,
 37,
 45,
 42,
 32,
 35,
 43,
 38,
 17,
 9,
 29,
 15,
 8,
 20,
 31,
 22,
 4,
 36,
 7,
 0,
 28,
 27,
 3,
 40,
 16,
 44,
 26,
 25,
 30,
 12,
 39,
 2,
 6,
 19,
 1]

In [231]:
#merge of 2 ranking
A = np.array(list(zip(image_index_ranking_x, image_index_ranking_y)))
A

array([[ 8, 21],
       [28, 13],
       [ 1, 11],
       [17, 14],
       [21,  5],
       [ 2, 33],
       [35, 18],
       [15, 24],
       [46, 34],
       [32, 23],
       [44, 41],
       [ 4, 46],
       [24, 10],
       [ 5, 37],
       [10, 45],
       [26, 42],
       [25, 32],
       [12, 35],
       [37, 43],
       [ 3, 38],
       [27, 17],
       [ 0,  9],
       [23, 29],
       [39, 15],
       [40,  8],
       [19, 20],
       [ 9, 31],
       [31, 22],
       [42,  4],
       [41, 36],
       [29,  7],
       [ 6,  0],
       [22, 28],
       [13, 27],
       [30,  3],
       [33, 40],
       [20, 16],
       [14, 44],
       [16, 26],
       [45, 25],
       [18, 30],
       [43, 12],
       [34, 39],
       [36,  2],
       [38,  6],
       [ 7, 19],
       [11,  1]])

In [243]:
np.std((1,2,3))

0.816496580927726

In [ ]:
for i in keypoints_test:
    np.std((i[])

## Criteria: someone is showing its profile

In [240]:
for image in keypoints_test:
    print(image)

[[0.71390643 0.44717513 0.32174302]
 [0.80835382 0.25937053 0.25608216]
 [0.63099105 0.77646639 0.15029388]
 [0.61154956 0.00109762 0.24544539]
 [0.28166745 0.27729974 0.42479885]
 [0.5938729  0.86600275 0.67655574]
 [0.85980872 0.41780143 0.69877459]
 [0.06981228 0.61122183 0.59397671]
 [0.228037   0.48814475 0.83555314]
 [0.80727272 0.50700598 0.38177026]
 [0.76921421 0.4983494  0.60102854]
 [0.54466528 0.1260939  0.51435233]
 [0.7348108  0.30501931 0.22845424]
 [0.13785591 0.63102543 0.89471167]
 [0.06410172 0.96411482 0.07929425]
 [0.02401791 0.02063123 0.90695511]
 [0.05069392 0.77771327 0.59106021]]
[[0.1240782  0.85407834 0.28978534]
 [0.1644787  0.52852075 0.78461518]
 [0.07020176 0.03849731 0.13515064]
 [0.22008465 0.4014892  0.21948817]
 [0.65808091 0.95391107 0.302088  ]
 [0.11602902 0.95331069 0.68512543]
 [0.80653167 0.01368245 0.86501516]
 [0.10718379 0.34451105 0.17965074]
 [0.00940739 0.8155064  0.62238208]
 [0.0569709  0.67982541 0.86911183]
 [0.50127521 0.24667583 0.8

In [197]:
min_distance_y_index

21

In [194]:
min(horizontal_shoulder)

0.02384719244079625

In [188]:
max_distance_x

0.8112596102206585

In [187]:
distance_shoulder

[0.26593582203219734,
 0.6905026545483369,
 0.5917638823610747,
 0.28471162790474114,
 0.4035844766626834,
 0.3600310244644006,
 0.12218439860604347,
 0.017488494004744615,
 0.8112596102206585,
 0.20107714612747685,
 0.34851517305250135,
 0.0031004554570213116,
 0.30577120387235335,
 0.10563523931682628,
 0.054226761784006206,
 0.5713718385233504,
 0.04968481830783833,
 0.6337683214373103,
 0.04091515207919805,
 0.20361385632996964,
 0.07312864002646446,
 0.6299300747615119,
 0.10800875128709331,
 0.2348305856755536,
 0.36158804884890394,
 0.32623617277685035,
 0.33951350510374545,
 0.2846168897768314,
 0.7663636840159467,
 0.12338627566271065,
 0.10328050363696317,
 0.16786495252897127,
 0.5339732066252992,
 0.10150998281982127,
 0.03683779450528102,
 0.5832312127185528,
 0.031772762002017396,
 0.3052915903603046,
 0.024347596113528436,
 0.2316720401649266,
 0.20448335639053883,
 0.1537240088783669,
 0.15988539495078968,
 0.03841263274515094,
 0.5173809441740697,
 0.04127273702758216,